//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarWah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado_Roles
    {
        public int Codigo { get; set; }
        public int EmpleadoId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Role Role { get; set; }
    }
}
