//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarWah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaDetail
    {
        public int Codigo { get; set; }
        public Nullable<int> VehiculoId { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public int Lavado { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> ITBIS { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual TipoLavado TipoLavado { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
